---
name: "L1 N-HO to L2 N-HO Transfer"
description: "Northern Halo to Halo transfer with small execution errors and small initial/final covariance, limited phasing"
dynamics:
  type: "CR3BP"
  sys_param_file: '../CR3BP_dev/EarthMoon_System/EMsys.yaml'
integration:
  a_tol: 1.e-13
  r_tol: 1.e-13
  int_save: 32
  mc_div: 2
segments: 41
MC_trials: 500
boundary_conditions:
  t0: "2026-01-01T00:00:00"
  tf: "2026-02-01T00:00:00"
  initial_orbit:
    family_path: '../CR3BP_dev/EarthMoon_System/L1_N_Halo.h5'
    Orb_ID: 145
    Start_Idx: 0
  final_orbit:
    family_path: '../CR3BP_dev/EarthMoon_System/L2_N_Halo.h5'
    Orb_ID: 30
    Start_Idx: 0
  type: "free"
  alpha:
    min: 0.0
    max: 1.0
  beta:
    min: 0.0
    max: 1.0
engine:
  m0: 200
  Isp: 3337
  T_max: .2
uncertainty:
  covariance:
    initial:
      pos_sig: 1
      vel_sig: .01
      mass_sig: 1.e-12
    target:
      pos_sig: 10
      vel_sig: .02
      mass_sig: 60
  acc_sig: 1.e-11
  gates:
    fixed_mag: 1.e-3
    prop_mag: 1.e-3
    fixed_point: 1.e-3
    prop_point: 1.e-3
  eps: .001
constraints: 
  col_avoid:
    parameters:
      r_obs: [384967.8803361727, 0., 0.]
      safe_d: 1737.5
    det:
      bool: true
    stat:
      bool: false
      UT:
        alpha: 1.0
        beta: 2.0
        kappa: 4.0
SNOPT:
  major_opt_tol: 1.e-3 # Change this one for speed/accuracy tradeoff
  major_feas_tol: 1.e-6
  minor_feas_tol: 1.e-6
  major_iter_limit: 10000
  partial_price: 1 # Impacts the number of variables SNOPT changes each iterations
  linesearch_tol: 1.e-3 # Impacts how large of a step SNOPT takes in the variables per iterations
  function_prec: 1.e-11